GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNzc2N2NlMTMtYThjNS00YzAxLTlkMjktOTdjMzkwNDZhYmFkIiwiZnVsbG5hbWUiOiJZdWxpbmFyIE51ciBSYWhtYXdhdGkiLCJ1c2VybmFtZSI6Inl1bGluYXJudXIiLCJpYXQiOjE3MjA2Njg2MzAsImV4cCI6MTcyMDY2ODY2MH0.BtfTz542kafsD4S5OSYWzkVLp7ab0lYCx8HuEHl5cXA
###
POST http://localhost:5000/register
Content-Type: application/json

{
    "fullname": "Yulinar Nur Rahmawati",
    "username": "yulinarnur",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "yulinarnur",
    "password": "12345678"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
