GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXVpZCI6ImUzN2VlNGU3LTQ5Y2UtNDg5Zi04YTUzLTU2YjBmNjJhMzEyZSIsImZ1bGxuYW1lIjoiSW50YW4iLCJ1c2VybmFtZSI6ImludGFuIiwiaWF0IjoxNzIwNjczOTU0LCJleHAiOjE3MjA2Nzc1NTR9.72FgUIsUp3AdycbuY5VO3U0kzLLhNItD7imRLLFAvnI

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "fullname": "Intan",
    "username": "intan",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "intan",
    "password": "12345678"
}

###
GET http://localhost:5000/token

###
GET http://localhost:5000/currentUser

###
DELETE http://localhost:5000/logout
